name: Node.js CI Manual

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm version patch --no-git-tag-version --force
      - run: git add --all
      - run: git config user.email "noreply@github.com"
      - run: git config user.name "GitHub Workflow"
      - run: git commit --allow-empty -m "Version Bump"
      - run: git checkout --orphan release
      - run: sed -i "2s/GenLite/GenLite-${{github.repository_owner}}/" userscript-banner.txt
      - run: sed -i "3s/GenLite/GenLite-${{github.repository_owner}}/" userscript-banner.txt
      - run: cat userscript-banner.txt
      - run: npm i
      - run: npm run build:nopatch --if-present
      - run: git add dist -f
      - run: git commit --allow-empty -m "New Release"
      - run: git push origin release -f
